# Generated by Django 6.1 on 2026-09-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arsip',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='arsip/%Y/%m/'),
        ),
    ]
